// @ts-check
'use strict';

/** @type {Record<string, import('../types').FrameworkTemplate>} */
const JS_FRAMEWORKS = {
  'nextjs': {
    id: 'nextjs',
    name: 'Next.js',
    icon: '⬛',
    lang: 'js',
    description: 'Framework React con SSR, SSG y App Router',
    version: '15.x',
    port: 3000,
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['app', 'app/components', 'public', 'lib'],
    files: {
      'app/page.tsx':
`export default function Home() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Welcome to {PROJECT_NAME}</h1>
      <p>Edit <code>app/page.tsx</code> to get started.</p>
    </main>
  );
}
`,
      'app/layout.tsx':
`import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '{PROJECT_NAME}',
  description: 'Generated by Framework Project Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
      'app/components/Header.tsx':
`export default function Header({ title }: { title: string }) {
  return (
    <header style={{ borderBottom: '1px solid #eee', padding: '1rem' }}>
      <h2>{title}</h2>
    </header>
  );
}
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@types/node": "^20"
  }
}
`,
      'tsconfig.json':
`{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
      'next.config.js':
`/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
`,
      '.env.local.example':
`NEXT_PUBLIC_APP_NAME={PROJECT_NAME}
NEXT_PUBLIC_API_URL=http://localhost:3000/api
`,
    },
  },

  'react-vite': {
    id: 'react-vite',
    name: 'React + Vite',
    icon: '⚛️',
    lang: 'js',
    description: 'React 19 con Vite para desarrollo ultrarrápido',
    version: '19.x',
    port: 5173,
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['src', 'src/components', 'src/hooks', 'public'],
    files: {
      'src/App.jsx':
`import { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <h1>{PROJECT_NAME}</h1>
      <p>Edit <code>src/App.jsx</code> to get started.</p>
      <button onClick={() => setCount(c => c + 1)}>
        Count: {count}
      </button>
    </div>
  );
}

export default App;
`,
      'src/App.css':
`* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background: #f9f9f9;
}

.App {
  text-align: center;
  padding: 2rem;
}

.App h1 {
  color: #333;
}

button {
  padding: 0.5rem 1.25rem;
  background: #646cff;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 1rem;
}

button:hover {
  background: #535bf2;
}
`,
      'src/main.jsx':
`import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
      'index.html':
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{PROJECT_NAME}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
      'vite.config.js':
`import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0"
  }
}
`,
      '.env.example': `VITE_APP_NAME={PROJECT_NAME}\nVITE_API_URL=http://localhost:3000\n`,
    },
  },

  'nestjs': {
    id: 'nestjs',
    name: 'NestJS',
    icon: '🐱',
    lang: 'js',
    description: 'Framework Node.js progresivo con arquitectura Angular-style',
    version: '10.x',
    port: 3000,
    enabled: true,
    templates: ['api'],
    architectures: ['standard'],
    enabled: true,
    templates: ['api'],
    architectures: ['standard'],
    folders: ['src', 'src/modules', 'test'],
    files: {
      'src/main.ts':
`import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const port = process.env.PORT ?? 3000;
  await app.listen(port);
  console.log(\`{PROJECT_NAME} running on http://localhost:\${port}\`);
}
bootstrap();
`,
      'src/app.module.ts':
`import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
`,
      'src/app.controller.ts':
`import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @Get('health')
  getHealth(): { status: string } {
    return { status: 'ok' };
  }
}
`,
      'src/app.service.ts':
`import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'Hello from {PROJECT_NAME}!';
  }
}
`,
      'package.json': JSON.stringify({
  name: '{PROJECT_NAME}',
  version: '0.0.1',
  private: true,
  scripts: {
    start: 'node dist/main',
    'start:dev': 'nest start --watch',
    build: 'nest build',
    lint: 'eslint "{src,apps,libs,test}/**/*.ts" --fix',
  },
  dependencies: {
    '@nestjs/common': '^10.0.0',
    '@nestjs/core': '^10.0.0',
    '@nestjs/platform-express': '^10.0.0',
    'reflect-metadata': '^0.2.0',
    rxjs: '^7.8.1',
  },
  devDependencies: {
    '@nestjs/cli': '^10.0.0',
    '@nestjs/schematics': '^10.0.0',
    '@types/express': '^5.0.0',
    '@types/node': '^20.0.0',
    typescript: '^5.0.0',
  },
}, null, 2),
      'tsconfig.json':
`{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
`,
      'nest-cli.json':
`{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true
  }
}
`,
      '.env.example': `PORT=3000\nNODE_ENV=development\nDATABASE_URL=postgres://user:password@localhost:5432/{PROJECT_NAME}\n`,
    },
  },

  'express': {
    id: 'express',
    name: 'Express',
    icon: '🚂',
    lang: 'js',
    description: 'Framework minimalista para APIs Node.js',
    version: '5.x',
    port: 3000,
    enabled: true,
    templates: ['api'],
    architectures: ['standard'],
    enabled: true,
    templates: ['api'],
    architectures: ['standard'],
    folders: ['src', 'src/routes', 'src/middleware', 'src/models', 'tests'],
    files: {
      'src/index.js':
`const express = require('express');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.get('/', (req, res) => {
  res.json({ message: 'Hello from {PROJECT_NAME}!', version: '1.0.0' });
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

const server = app.listen(PORT, () => {
  console.log(\`{PROJECT_NAME} running on http://localhost:\${PORT}\`);
});

module.exports = { app, server };
`,
      'src/routes/index.js':
`const { Router } = require('express');

const router = Router();

router.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

module.exports = router;
`,
      'tests/app.test.js':
`const { app } = require('../src/index');

// Simple smoke test — run with: node tests/app.test.js
const http = require('http');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log('✅', name);
    passed++;
  } catch (e) {
    console.log('❌', name, '-', e.message);
    failed++;
  }
}

async function runTests() {
  // Test that app module exports correctly
  test('app is defined', () => {
    if (!app) throw new Error('app not exported');
  });

  console.log(\`\\n\${passed} passed, \${failed} failed\`);
  process.exit(failed > 0 ? 1 : 0);
}

runTests();
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "1.0.0",
  "private": true,
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "test": "node tests/app.test.js"
  },
  "dependencies": {
    "express": "^5.0.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.0"
  }
}
`,
      '.env.example': `PORT=3000\nNODE_ENV=development\nDATABASE_URL=sqlite:./dev.db\n`,
    },
  },

  'vue-vite': {
    id: 'vue-vite',
    name: 'Vue 3 + Vite',
    icon: '💚',
    lang: 'js',
    description: 'Vue 3 con Composition API y Vite',
    version: '3.x',
    port: 5173,
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['src', 'src/components', 'src/views', 'public'],
    files: {
      'index.html':
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{PROJECT_NAME}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`,
      'src/App.vue':
`<template>
  <div id="app">
    <h1>{{ title }}</h1>
    <p>Edit <code>src/App.vue</code> to get started.</p>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const title = ref('{PROJECT_NAME}');
</script>

<style>
#app {
  font-family: system-ui, -apple-system, sans-serif;
  text-align: center;
  padding: 2rem;
}
</style>
`,
      'src/main.js':
`import { createApp } from 'vue';
import App from './App.vue';

createApp(App).mount('#app');
`,
      'src/components/HelloWorld.vue':
`<template>
  <div class="hello">
    <h2>{{ msg }}</h2>
  </div>
</template>

<script setup>
defineProps({
  msg: String,
});
</script>
`,
      'vite.config.js':
`import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [vue()],
});
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.33"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.0",
    "vite": "^5.0.0"
  }
}
`,
      '.env.example': `VITE_APP_NAME={PROJECT_NAME}\nVITE_API_BASE_URL=http://localhost:3000\n`,
    },
  },

  'sveltekit': {
    id: 'sveltekit',
    name: 'SvelteKit',
    icon: '🔴',
    lang: 'js',
    description: 'Framework fullstack con compilación reactiva',
    version: '2.x',
    port: 5173,
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['src', 'src/routes', 'src/lib', 'static'],
    files: {
      'src/routes/+page.svelte':
`<script>
  let count = $state(0);
</script>

<svelte:head>
  <title>{PROJECT_NAME}</title>
</svelte:head>

<main>
  <h1>Welcome to {PROJECT_NAME}</h1>
  <p>Edit <code>src/routes/+page.svelte</code> to get started.</p>
  <button onclick={() => count++}>Clicks: {count}</button>
</main>

<style>
  main {
    font-family: system-ui, sans-serif;
    text-align: center;
    padding: 2rem;
  }
</style>
`,
      'src/routes/+layout.svelte':
`<slot />
`,
      'src/lib/index.js':
`export const appName = '{PROJECT_NAME}';
`,
      'static/.gitkeep': '',
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "0.0.1",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "svelte": "^5.0.0",
    "vite": "^5.0.0"
  }
}
`,
      'svelte.config.js':
`import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
  },
};

export default config;
`,
      'vite.config.js':
`import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
});
`,
      '.env.example': `PUBLIC_APP_NAME={PROJECT_NAME}\nPRIVATE_DATABASE_URL=sqlite:./dev.db\n`,
    },
  },

  'astro': {
    id: 'astro',
    name: 'Astro',
    icon: '🌌',
    lang: 'js',
    description: 'Framework para sitios con contenido estático ultrarrápido',
    version: '5.x',
    port: 4321,
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['src', 'src/pages', 'src/components', 'src/layouts', 'public'],
    files: {
      'src/pages/index.astro':
`---
import Layout from '../layouts/Layout.astro';
---
<Layout title="{PROJECT_NAME}">
  <h1>Welcome to {PROJECT_NAME}</h1>
  <p>Edit <code>src/pages/index.astro</code> to get started.</p>
</Layout>
`,
      'src/layouts/Layout.astro':
`---
const { title } = Astro.props;
---
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{title}</title>
    <style>
      body { font-family: system-ui, sans-serif; padding: 2rem; }
    </style>
  </head>
  <body>
    <slot />
  </body>
</html>
`,
      'src/components/Card.astro':
`---
const { title, body } = Astro.props;
---
<div class="card">
  <h2>{title}</h2>
  <p>{body}</p>
</div>

<style>
  .card { border: 1px solid #eee; border-radius: 8px; padding: 1rem; }
</style>
`,
      'public/.gitkeep': '',
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "astro": "^5.0.0"
  }
}
`,
      'astro.config.mjs':
`import { defineConfig } from 'astro/config';

export default defineConfig({});
`,
      '.env.example': `PUBLIC_APP_NAME={PROJECT_NAME}\nPUBLIC_API_URL=http://localhost:3000\n`,
    },
  },

  'nuxt3': {
    id: 'nuxt3',
    name: 'Nuxt 3',
    icon: '💚',
    lang: 'js',
    description: 'Framework fullstack Vue con SSR y generación estática',
    version: '3.x',
    port: 3000,
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: false,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['pages', 'components', 'composables', 'assets', 'public', 'server/api'],
    files: {
      'pages/index.vue':
`<template>
  <div>
    <h1>{{ title }}</h1>
    <p>Edit <code>pages/index.vue</code> to get started.</p>
    <NuxtLink to="/about">About</NuxtLink>
  </div>
</template>

<script setup>
const title = ref('{PROJECT_NAME}')
</script>
`,
      'pages/about.vue':
`<template>
  <div>
    <h1>About {PROJECT_NAME}</h1>
    <NuxtLink to="/">Home</NuxtLink>
  </div>
</template>
`,
      'app.vue':
`<template>
  <div>
    <NuxtPage />
  </div>
</template>
`,
      'server/api/hello.get.ts':
`export default defineEventHandler(() => {
  return {
    message: 'Hello from {PROJECT_NAME}!',
    timestamp: new Date().toISOString(),
  }
})
`,
      'nuxt.config.ts':
`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: true,
  runtimeConfig: {
    public: {
      appName: '{PROJECT_NAME}',
    },
  },
  compatibilityDate: '2025-01-01',
})
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.14.0",
    "vue": "^3.5.33"
  }
}
`,
      '.env.example': `NUXT_APP_NAME={PROJECT_NAME}\nNUXT_PUBLIC_API_BASE=http://localhost:3000\n`,
    },
  },

  'hono': {
    id: 'hono',
    name: 'Hono',
    icon: '🔥',
    lang: 'js',
    description: 'Framework web ultrarrápido para edge y Node.js',
    version: '4.x',
    port: 3000,
    enabled: false,
    templates: ['api'],
    architectures: ['standard'],
    enabled: false,
    templates: ['api'],
    architectures: ['standard'],
    folders: ['src', 'src/routes', 'src/middleware', 'test'],
    files: {
      'src/index.ts':
`import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger } from 'hono/logger';
import items from './routes/items';

const app = new Hono();

app.use('*', logger());
app.use('/api/*', cors());

app.get('/', (c) => c.json({ message: 'Hello from {PROJECT_NAME}!', version: '1.0.0' }));
app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));
app.route('/api/items', items);

const port = Number(process.env.PORT) || 3000;
console.log(\`{PROJECT_NAME} running on http://localhost:\${port}\`);

serve({ fetch: app.fetch, port });

export default app;
`,
      'src/routes/items.ts':
`import { Hono } from 'hono';

const items = new Hono();

const db = [
  { id: 1, name: 'Item One' },
  { id: 2, name: 'Item Two' },
];

items.get('/', (c) => c.json(db));

items.get('/:id', (c) => {
  const id = parseInt(c.req.param('id'));
  const item = db.find((i) => i.id === id);
  if (!item) return c.json({ error: 'Not found' }, 404);
  return c.json(item);
});

export default items;
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "start": "node dist/index.js",
    "build": "tsc"
  },
  "dependencies": {
    "@hono/node-server": "^1.0.0",
    "hono": "^4.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "tsx": "^4.0.0",
    "typescript": "^5.0.0"
  }
}
`,
      'tsconfig.json':
`{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "outDir": "dist",
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist"]
}
`,
      '.env.example': `PORT=3000\nNODE_ENV=development\n`,
    },
  },

  'angular': {
    id: 'angular',
    name: 'Angular',
    icon: '🔴',
    lang: 'js',
    description: 'Framework SPA completo con TypeScript y DI',
    version: '19.x',
    port: 4200,
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['src/app', 'src/app/components', 'src/environments', 'public'],
    files: {
      'src/main.ts':
`import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';

bootstrapApplication(AppComponent, appConfig).catch((e) => console.error(e));
`,
      'src/app/app.component.ts':
`import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = '{PROJECT_NAME}';
}
`,
      'src/app/app.component.html':
`<main>
  <header>
    <h1>Welcome to {{ title }}</h1>
  </header>
  <router-outlet />
</main>
`,
      'src/app/app.component.css':
`main {
  padding: 2rem;
  font-family: system-ui, -apple-system, sans-serif;
}

header {
  border-bottom: 2px solid #1976d2;
  margin-bottom: 2rem;
  padding-bottom: 1rem;
}

h1 {
  color: #1976d2;
  margin: 0;
}
`,
      'src/app/app.config.ts':
`import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
  ],
};
`,
      'src/app/app.routes.ts':
`import { Routes } from '@angular/router';

export const routes: Routes = [];
`,
      'src/index.html':
`<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <title>{PROJECT_NAME}</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
`,
      'src/styles.css':
`/* Global styles */
* {
  box-sizing: border-box;
}

body {
  margin: 0;
}
`,
      'angular.json':
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "{PROJECT_NAME}": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/{PROJECT_NAME}",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": ["zone.js"],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "css",
            "assets": [{ "glob": "**/*", "input": "public" }],
            "styles": ["src/styles.css"],
            "scripts": []
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": { "buildTarget": "{PROJECT_NAME}:build:production" },
            "development": { "buildTarget": "{PROJECT_NAME}:build:development" }
          },
          "defaultConfiguration": "development"
        }
      }
    }
  }
}
`,
      'tsconfig.json':
`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": false,
    "experimentalDecorators": true,
    "moduleResolution": "bundler",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "lib": ["ES2022", "dom"]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
`,
      'tsconfig.app.json':
`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": ["src/main.ts"],
  "include": ["src/**/*.d.ts"]
}
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development"
  },
  "dependencies": {
    "@angular/animations": "^19.0.0",
    "@angular/common": "^19.0.0",
    "@angular/compiler": "^19.0.0",
    "@angular/core": "^19.0.0",
    "@angular/forms": "^19.0.0",
    "@angular/platform-browser": "^19.0.0",
    "@angular/router": "^19.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^19.0.0",
    "@angular/cli": "^19.0.0",
    "@angular/compiler-cli": "^19.0.0",
    "typescript": "~5.6.0"
  }
}
`,
    },
  },
};

module.exports = { JS_FRAMEWORKS };
