// @ts-check
'use strict';

/** @type {import('../../types').FrameworkTemplate} */
const NEXTJS = {
    id: 'nextjs',
    name: 'Next.js',
    icon: '⬛',
    lang: 'js',
    description: 'Framework React con SSR, SSG y App Router',
    version: '15.x',
    port: 3000,
    enabled: true,
    templates: ['standard'],
    architectures: ['standard'],
    folders: ['app', 'app/components', 'public', 'lib'],
    files: {
      'app/page.tsx':
`export default function Home() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>Welcome to {PROJECT_NAME}</h1>
      <p>Edit <code>app/page.tsx</code> to get started.</p>
    </main>
  );
}
`,
      'app/layout.tsx':
`import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '{PROJECT_NAME}',
  description: 'Generated by Framework Project Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
      'app/components/Header.tsx':
`export default function Header({ title }: { title: string }) {
  return (
    <header style={{ borderBottom: '1px solid #eee', padding: '1rem' }}>
      <h2>{title}</h2>
    </header>
  );
}
`,
      'package.json':
`{
  "name": "{PROJECT_NAME}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@types/node": "^20"
  }
}
`,
      'tsconfig.json':
`{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
      'next.config.js':
`/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
`,
      '.env.local.example':
`NEXT_PUBLIC_APP_NAME={PROJECT_NAME}
NEXT_PUBLIC_API_URL=http://localhost:3000/api
`,
    },
  };

module.exports = { NEXTJS };
